//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoIDAII.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesETM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientesETM()
        {
            this.CuentasPorCobrarETM = new HashSet<CuentasPorCobrarETM>();
        }
    
        public int id { get; set; }
        public string nomEmpresaE { get; set; }
        public string nomContactoE { get; set; }
        public string telefonoE { get; set; }
        public string correoE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentasPorCobrarETM> CuentasPorCobrarETM { get; set; }
    }
}
