//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoIDAII.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentasPorCobrarETM
    {
        public int id { get; set; }
        public string noCotizacionE { get; set; }
        public string divisionE { get; set; }
        public string ordenCompraE { get; set; }
        public double cantidadE { get; set; }
        public double cantidadIVAE { get; set; }
        public System.DateTime fechaEmisionE { get; set; }
        public int diasCreditoE { get; set; }
        public System.DateTime diaEstimadoE { get; set; }
        public System.DateTime diaTransferenciaE { get; set; }
        public string observacionesE { get; set; }
        public string causaE { get; set; }
        public string estatusE { get; set; }
        public string mesE { get; set; }
        public string bancoE { get; set; }
        public Nullable<int> id_ClienteETM { get; set; }
    
        public virtual ClientesETM ClientesETM { get; set; }
    }
}
