//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoIDAII.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentasPorCobrarIDAII
    {
        public int id { get; set; }
        public string noCotizacion { get; set; }
        public string division { get; set; }
        public string ordenCompra { get; set; }
        public double cantidad { get; set; }
        public double cantidadIVA { get; set; }
        public System.DateTime fechaEmision { get; set; }
        public int diasCredito { get; set; }
        public System.DateTime diaEstimado { get; set; }
        public System.DateTime diaTransferencia { get; set; }
        public string observaciones { get; set; }
        public string causa { get; set; }
        public string estatus { get; set; }
        public string mes { get; set; }
        public string banco { get; set; }
        public Nullable<int> id_Cliente { get; set; }
    
        public virtual ClientesIDAII ClientesIDAII { get; set; }
        public virtual ClientesIDAII ClientesIDAII1 { get; set; }
    }
}
