//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoIDAII.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialesETM
    {
        public int id { get; set; }
        public string proveedorE { get; set; }
        public string mesE { get; set; }
        public double subtotalE { get; set; }
        public double ivaE { get; set; }
        public double montoE { get; set; }
        public string facturaE { get; set; }
        public System.DateTime fecha_facE { get; set; }
        public int dias_creditoE { get; set; }
        public System.DateTime fecha_limE { get; set; }
        public string bancoE { get; set; }
        public string estatusE { get; set; }
    }
}
